#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

plugins:
   - async-await

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - "!.*"
  - "**/node_modules/.*"

###############
# Parser vars #
###############
parserOptions:
  ecmaVersion: 2020
  sourceType: module

extends:
  # http://eslint.org/docs/user-guide/configuring#using-eslintrecommended
  - eslint:recommended
  # https://www.npmjs.com/package/eslint-config-airbnb-base
  - airbnb/base